banner:
  location: banner.txt

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${API_PAYMENT_MONGO_URL}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    
config:
  openapi:
    title: API (api-payment)
    description: API Backend api-payment.
    terms: https://google.com
    licence: apache 2.0
    licenceUrl: https://google.com
    version: 1.0
    contact:
      name: CBProjects
      url: https://cbprojects.com
      email: contact@cbprojects.com

rest:
  request:
    header:
      key: API_PAYMENT_SERVER
      version: 1.0.0
  
api:
  stripe:
    public-key: ${API_STRIPE_PUBLIC_KEY}
    private-key: ${API_STRIPE_PRIVATE_KEY} 

server:
  port: 8443
  servlet:
    context-path: /api-payment-server
  ssl: 
    key-store: classpath:cbaeneprojects.pfx
    key-store-password: ${SSL_PASSWORD}
    keyStoreType: PKCS12